shell = "/bin/zsh"
working_directory = "/Users/ethanwalker/src"
live_config_reload = true

[ font ]
size = 16

[ font.normal ]
family ="FiraCode Nerd Font Mono"
style = "Retina"

# [font.bold]
# style = "Retina"

[colors.primary]
background = "#000000"
foreground = "#dfdfdf"

# [colors]
# draw_bold_text_with_bright_colors = true

# [debug]
# render_timer = true
